INSERT INTO [#MONITOR_CCS_STATUS] ([Schema],[Tablename],[compagny],[CCS_ID],[CCS_KEY],[CCS_CCM_CODE],[CCS_CCM_NAME],[CCS_USR_LOGIN],[CCS_USR_NAME],[CCS_DATE],[CCS_STATUS],[CCS_COMMENT],[CCS_FILE]) 
  SELECT @SCHEMANAME,@FULLNAME,@LABEL,[CCS_ID],[CCS_KEY],[CCS_CCM_CODE],[CCS_CCM_NAME],[CCS_USR_LOGIN],[CCS_USR_NAME],[CCS_DATE],[CCS_STATUS],[CCS_COMMENT],[CCS_FILE] 
  FROM {0} x 
  WHERE not ( ccs_usr_login = '' and ccs_status = 1 )
